initial commit
shopgate-professional-services/ext-category-drawer pull request #1
Opened 2022-07-27 13:40 UTC by Phmank

2022-07-28 06:47 UTC, fkloes requested changes

2022-07-28 06:47 UTC, fkloes commented on frontend/subscriptions/index.js
> +  let windowReady = false;
That's not used anywhere. Please remove this line and the event listener below.

2022-07-28 06:47 UTC, fkloes commented on frontend/selectors/index.js
> +export const isSearchBarVisible = createSelector(
This selector is not used. You can also remove the "searchBarWhitelist" from the constants.

2022-07-28 06:47 UTC, fkloes commented on frontend/constants.js
> +export const RECEIVE_CATEGORY_TREE = 'RECEIVE_CATEGORY_TREE';
I guess you can remove all constants except the actions.

2022-07-28 06:47 UTC, fkloes commented on frontend/components/NavDrawerCategoriesTree/index.jsx
> +  maxCategoryNesting: 3,
Are those settings a candidate for an extension setting?

2022-07-28 06:47 UTC, fkloes commented on frontend/components/NavDrawerCategoriesTree/components/Item/index.jsx
> +    color: '#85754e',
That's a golden color from the original extension. It's used to highlight active tree entries. You can only see it when the extension is deployed with PWA < 7. Otherwise it's black because of the css variables below.

Shouldn't this be configurable?.

2022-07-28 06:47 UTC, fkloes commented on frontend/components/NavDrawerCategoriesTree/components/CategoriesItem/index.jsx
> +    color: '#85754e',
That's a golden color from the original extension. It's used for the chevrons that indicate that a category is opened. Shouldn't this be configurable?.

2022-07-28 06:47 UTC, fkloes commented on frontend/components/NavDrawerCategories/index.jsx
> +const NavDrawerCategories = () => (
The contents of this folder are not used right now. It contains the initial version of the category navigation that was replaced by the category tree.

I didn't do a review of it yet, since i guess you'll delete it.

2022-07-28 06:47 UTC, fkloes commented on README.md
> +Adds a Burger Icon on the top left to open a Category Drawer. The Category Drawer slides in from the left side of the App.
The extension uses a portal position of the persistent-search-bar extension. Without this extension it will not work in the current state. 

Additionally the icon is only applied for the iOS theme, since the category tree is rendered inside a nav drawer which is already occupied at the gmd theme.

I think the readme should mention those facts.

2022-07-28 06:47 UTC, fkloes commented on extension/constants.js
> +const STORAGE_KEY = 'phi.categoryTree'
I think this key should be changed.

2022-07-28 06:47 UTC, fkloes commented on extension/lib/cache.js
> +const { hasValue } = require('../helpers')
Seems that this file isn't used anymore. You would notice it, since it tries to import a file that is not included to the extension.

2022-07-28 06:47 UTC, fkloes commented on extension/test/unit/cache-test.js
> +const sinon = require('sinon')
Seems that this file isn't used anymore. It tests a cache system which is not used by the extension. Additionally it relies on `chai-as-promised` which is not part of the package.json.

2022-07-28 06:47 UTC, fkloes commented on extension/test/unit/helpers-test.js
> +const assert = require('assert')
Seems that this file isn't used anymore. It contains tests for a file which is not included to the extension.

2022-07-28 06:47 UTC, fkloes commented on pipelines/shopgate.category-drawer.fetchCategoryTree.v1.json
> +{
It seems that this pipeline is not used.

2022-07-28 06:47 UTC, fkloes commented on frontend/portals/NavDrawer/index.jsx
> +  <NavDrawer onOpen={onOpen} onClose={onClose}>
The `SearchBurgerIcon` component has a protection that it's not rendered in the GMD theme

```
  if (!isIOS) {
    return null;
  }
```
I think this component also needs that. I had situations where on GMD the burger icon was not visible, but the category drawer opened behind the regular drawer in that theme. When this drawer was closed, the category tree was visible.

2022-07-28 06:47 UTC, fkloes commented on pipelines/shopgate.catalog.getRootCategories.v1.json
> +  "version": "1",
It seems that this pipeline isn't used be the extension.

2022-07-28 06:47 UTC, fkloes commented on extension/package.json
> +  "name": "@shopgate-project/category-drawer",
This can be reduced to something like that

```
{
  "name": "@shopgate-project/category-drawer",
  "version": "1.0.0",
  "description": "Adds BurgerIcon to open a Category Drawer.",
  "license": "Apache-2.0",
  "scripts": {
    "lint": "eslint --ignore-path ../.gitignore --ext .js ."
  },
  "devDependencies": {
    "eslint": "~5.12.0",
    "eslint-config-standard": "^11.0.0",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-standard": "^3.0.1",
    "standard": "^10.0.3"
  },
  "dependencies": {
    "@shopgate/bigapi-requester": "^2.1.0",
    "request-promise-native": "^1.0.5"
  }
}
```

2022-08-02 06:18 UTC, Phmank commented on frontend/subscriptions/index.js
> +  let windowReady = false;
removed

2022-08-02 06:22 UTC, Phmank commented on frontend/selectors/index.js
> +export const isSearchBarVisible = createSelector(
removed

2022-08-02 06:23 UTC, Phmank commented on frontend/constants.js
> +export const RECEIVE_CATEGORY_TREE = 'RECEIVE_CATEGORY_TREE';
removed

2022-08-02 06:29 UTC, Phmank commented on frontend/components/NavDrawerCategoriesTree/components/Item/index.jsx
> +    color: '#85754e',
use themconfig.colors (primary) now

2022-08-02 06:36 UTC, Phmank commented on frontend/components/NavDrawerCategoriesTree/components/CategoriesItem/index.jsx
> +    color: '#85754e',
use themconfig.colors (primary) now

2022-08-02 06:37 UTC, Phmank commented on frontend/components/NavDrawerCategories/index.jsx
> +const NavDrawerCategories = () => (
deleted

2022-08-02 06:39 UTC, Phmank commented on extension/constants.js
> +const STORAGE_KEY = 'phi.categoryTree'
changed

2022-08-02 06:47 UTC, Phmank commented on extension/lib/cache.js
> +const { hasValue } = require('../helpers')
added file

2022-08-02 06:49 UTC, Phmank commented on extension/test/unit/helpers-test.js
> +const assert = require('assert')
removed

2022-08-02 06:49 UTC, Phmank commented on extension/test/unit/cache-test.js
> +const sinon = require('sinon')
removed

2022-08-03 05:06 UTC, Phmank commented on frontend/portals/NavDrawer/index.jsx
> +  <NavDrawer onOpen={onOpen} onClose={onClose}>
I implemented it into the NavDrawer component. NavDrawer doesn't open in the background anymore.

2022-08-03 05:14 UTC, Phmank commented on pipelines/shopgate.category-drawer.fetchCategoryTree.v1.json
> +{
removed

2022-08-03 05:16 UTC, Phmank commented on pipelines/shopgate.catalog.getRootCategories.v1.json
> +  "version": "1",
removed

2022-08-03 05:19 UTC, Phmank commented on extension/package.json
> +  "name": "@shopgate-project/category-drawer",
reduced.

2022-08-03 05:29 UTC, Phmank commented on README.md
> +Adds a Burger Icon on the top left to open a Category Drawer. The Category Drawer slides in from the left side of the App.
added information

2022-08-03 14:10 UTC, fkloes commented on pipelines/shopgate.category-drawer.fetchCategoryTree.v1.json
> +{
It seems that the pipeline is used by getCategory tree. Sorry... i'll put it bacl.

2022-08-03 14:36 UTC, fkloes approved these changes

2022-08-03 14:40 UTC, Phmank commented
First version

2022-08-03 14:40 UTC, merged